set(exename particle-to-grid)
set(P2G_SOURCES particle-to-grid.cpp p2g/run.cpp)
set(P2G_INCLUDES ${PROJECT_SOURCE_DIR}/main/src ${CSTONE_DIR} ${PROJECT_SOURCE_DIR}/extern/io ${MPI_CXX_INCLUDE_PATH})

add_executable(${exename} ${P2G_SOURCES})
target_include_directories(${exename} PUBLIC ${P2G_INCLUDES})
target_link_libraries(${exename} PRIVATE io OpenMP::OpenMP_CXX ${MPI_CXX_LIBRARIES})
install(TARGETS ${exename} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

if(CMAKE_CUDA_COMPILER)
    add_executable(${exename}-cuda ${P2G_SOURCES} mesh.cu)
    target_include_directories(${exename}-cuda PUBLIC ${P2G_INCLUDES})
    target_compile_definitions(${exename}-cuda PRIVATE USE_CUDA)
    if(GPU_DIRECT)
        target_compile_definitions(${exename}-cuda PRIVATE USE_GPU_DIRECT)
    endif()
    target_link_libraries(${exename}-cuda PRIVATE cstone_gpu io OpenMP::OpenMP_CXX ${MPI_CXX_LIBRARIES} CUDA::cudart)
    install(TARGETS ${exename}-cuda RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()
